name: Android CI

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  workflow_dispatch:
    inputs:
      should-publish:
        type: boolean
        description: "Do you want to publish the library?"
        default: false
        required: true

      release-version:
        type: string
        description: "Specify the version to release"
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to GitHub Package Registry 🚀
      run: bash ./gradlew :currencypicker:publish
      if: always() && (github.event.inputs.should-publish == 'true')
      env:
        GPR_USER: ${{ github.actor }}
        GPR_KEY: ${{ secrets.PAT_TOKEN }}
        RELEASE_VERSION: ${{ github.event.inputs.release-version }}
        
    # - name: Create Release ✅
    #   id: create_release
    #   if: always() && (github.event.inputs.should-publish == 'true')
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: ${{ github.ref }}
    #     draft: true
    #     prerelease: false
        
    - name: Upload Library AAR 🗳
      if: always() && (github.event.inputs.should-publish == 'true')
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
        repository: ${{ github.repository }}
        tag_name: ${{ github.event.inputs.release-version }}
        files: currencypicker/build/outputs/aar/currencypicker-release.aar
